const FORM_START_MARKER = "GT1_TONE_FORM_V0_1";
const FORM_END_MARKER = "END_GT1_TONE_FORM";
const MVP_CHAIN = "COMP,OD_DS,PREAMP,NS,EQ,DELAY,REVERB";

const REQUIRED_FIELDS = [
  "PATCH_NAME",
  "REFERENCE",
  "GUITARIST",
  "BAND",
  "SONG",
  "ALBUM_OR_ERA",
  "STYLE",
  "TONE_TYPE",
  "CONFIDENCE",
  "CHAIN",
  "COMP_ON",
  "COMP_TYPE",
  "COMP_SUSTAIN",
  "COMP_ATTACK",
  "COMP_TONE",
  "COMP_LEVEL",
  "OD_DS_ON",
  "OD_DS_TYPE",
  "OD_DS_DRIVE",
  "OD_DS_TONE",
  "OD_DS_BOTTOM",
  "OD_DS_EFFECT_LEVEL",
  "OD_DS_DIRECT_LEVEL",
  "PREAMP_ON",
  "PREAMP_TYPE",
  "PREAMP_GAIN",
  "PREAMP_LEVEL",
  "PREAMP_BASS",
  "PREAMP_MIDDLE",
  "PREAMP_TREBLE",
  "PREAMP_PRESENCE",
  "PREAMP_BRIGHT",
  "NS_ON",
  "NS_THRESHOLD",
  "NS_RELEASE",
  "EQ_ON",
  "EQ_LOW",
  "EQ_MID",
  "EQ_HIGH",
  "DELAY_ON",
  "DELAY_TYPE",
  "DELAY_TIME",
  "DELAY_FEEDBACK",
  "DELAY_LEVEL",
  "REVERB_ON",
  "REVERB_TYPE",
  "REVERB_TIME",
  "REVERB_LEVEL",
  "MASTER_LEVEL",
  "NOTES",
];

const YES_NO_FIELDS = [
  "COMP_ON",
  "OD_DS_ON",
  "PREAMP_ON",
  "NS_ON",
  "EQ_ON",
  "DELAY_ON",
  "REVERB_ON",
];

const TEXT_FIELDS = [
  "PATCH_NAME",
  "REFERENCE",
  "GUITARIST",
  "BAND",
  "SONG",
  "ALBUM_OR_ERA",
  "STYLE",
  "NOTES",
];

const ALLOWED_VALUES = {
  TONE_TYPE: [
    "base",
    "lead",
    "crunch",
    "clean",
    "metal",
    "rock",
    "fuzz",
    "solo",
    "outro",
  ],
  OD_DS_TYPE: [
    "MID BOOST",
    "CLEAN BST",
    "TREBLE BST",
    "CRUNCH",
    "NATURAL OD",
    "WARM OD",
    "FAT DS",
    "LEAD DS",
    "METAL DS",
    "OCT FUZZ",
    "A-DIST",
    "BLUES OD",
    "OD-1",
    "T-SCREAM",
    "TURBO OD",
    "DISTORTION",
    "RAT",
    "GUV DS",
    "DST+",
    "METAL ZONE",
    "60S FUZZ",
    "MUFF FUZZ",
  ],
  PREAMP_TYPE: [
    "NATURAL CLEAN",
    "FULL RANGE",
    "COMBO CRUNCH",
    "STACK CRUNCH",
    "HiGAIN STACK",
    "POWER DRIVE",
    "EXTREME LEAD",
    "CORE METAL",
    "JC-120",
    "TWEED",
    "DELUXE CRUNCH",
    "VO DRIVE",
    "VO LEAD",
    "MATCH DRIVE",
    "BG LEAD",
    "BG DRIVE",
    "MS1959 I",
    "MS1959 I+II",
    "R-FIER VINTAGE",
    "R-FIER MODERN",
    "T-AMP LEAD",
    "SLDN",
    "5150 DRIVE",
    "METAL LEAD",
  ],
  COMP_TYPE: [
    "BOSS",
    "HI-BAND",
    "LIGHT",
    "D-COMP",
    "ORANGE",
    "FAT",
    "MILD",
    "STEREO",
  ],
  REVERB_TYPE: [
    "AMBIENCE",
    "ROOM",
    "HALL 1",
    "HALL 2",
    "PLATE",
  ],
  DELAY_TYPE: [
    "STANDARD",
    "ANALOG",
    "TAPE",
    "MODULATE",
    "REVERSE",
  ],
  PREAMP_BRIGHT: [
    "ON",
    "OFF",
  ],
};

const NUMERIC_RANGES = {
  CONFIDENCE: { min: 0, max: 1, integer: false },
  COMP_SUSTAIN: { min: 0, max: 100, integer: true },
  COMP_ATTACK: { min: 0, max: 100, integer: true },
  COMP_TONE: { min: -50, max: 50, integer: true },
  COMP_LEVEL: { min: 0, max: 100, integer: true },
  OD_DS_DRIVE: { min: 0, max: 120, integer: true },
  OD_DS_TONE: { min: -50, max: 50, integer: true },
  OD_DS_BOTTOM: { min: -50, max: 50, integer: true },
  OD_DS_EFFECT_LEVEL: { min: 0, max: 100, integer: true },
  OD_DS_DIRECT_LEVEL: { min: 0, max: 100, integer: true },
  PREAMP_GAIN: { min: 0, max: 120, integer: true },
  PREAMP_LEVEL: { min: 0, max: 100, integer: true },
  PREAMP_BASS: { min: 0, max: 100, integer: true },
  PREAMP_MIDDLE: { min: 0, max: 100, integer: true },
  PREAMP_TREBLE: { min: 0, max: 100, integer: true },
  PREAMP_PRESENCE: { min: 0, max: 100, integer: true },
  NS_THRESHOLD: { min: 0, max: 100, integer: true },
  NS_RELEASE: { min: 0, max: 100, integer: true },
  EQ_LOW: { min: -20, max: 20, integer: true },
  EQ_MID: { min: -20, max: 20, integer: true },
  EQ_HIGH: { min: -20, max: 20, integer: true },
  DELAY_TIME: { min: 1, max: 2000, integer: true },
  DELAY_FEEDBACK: { min: 0, max: 100, integer: true },
  DELAY_LEVEL: { min: 0, max: 100, integer: true },
  REVERB_TIME: { min: 0.1, max: 10, integer: false },
  REVERB_LEVEL: { min: 0, max: 100, integer: true },
  MASTER_LEVEL: { min: 0, max: 100, integer: true },
};

const REQUIRED_FIELD_SET = new Set(REQUIRED_FIELDS);
const YES_NO_FIELD_SET = new Set(YES_NO_FIELDS);

module.exports = {
  ALLOWED_VALUES,
  FORM_END_MARKER,
  FORM_START_MARKER,
  MVP_CHAIN,
  NUMERIC_RANGES,
  REQUIRED_FIELDS,
  REQUIRED_FIELD_SET,
  TEXT_FIELDS,
  YES_NO_FIELDS,
  YES_NO_FIELD_SET,
};
